export {default as Navbar} from './navigation/Navbar'
export {default as Home} from './pages/Home'
export {default as Login} from './pages/Login'
export {default as Form1} from './pages/forms/Form1'
export {default as App2} from './pages/forms/form2/App2'
export {default as Form3} from './pages/forms/Form3'
export {default as Form4} from './pages/forms/Form4'
export { default as Form5 } from './pages/forms/Form5'
export {default as NoPageMatch} from './pages/NoPageMatch'
export {default as Signup} from './pages/Signup'